version: 2
jobs:
  client:
    docker:
      - image: meteor/circleci:latest
    steps:
      - checkout
      - run: 'curl https://install.meteor.com | /bin/sh'
      - run: 'meteor npm install'
      - run: 'npm test'
      - store_artifacts:
          path: '.reports/'
      - store_test_results:
          path: '.reports/jest/'
  server:
    docker:
      - image: meteor/circleci:latest
    steps:
      - checkout
      - run: 'curl https://install.meteor.com | /bin/sh'
      - run: 'meteor npm install'
      - run: 'meteor test --once --driver-package meteortesting:mocha'
workflows:
  version: 2
  client:
    jobs:
      - client
  server:
    jobs:
      - server
